# Generated by Django 5.1.7 on 2025-03-20 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitybooking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='facilitybooking',
            old_name='resident',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='facilitybooking',
            name='facility',
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='facility_name',
            field=models.CharField(default='Community Hall', max_length=255),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facilitybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
