# Generated by Django 5.1.7 on 2025-03-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_booking_date_facilitybooking_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitybooking',
            old_name='user',
            new_name='resident',
        ),
    ]
