# Generated by Django 5.1.7 on 2025-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_rename_user_facilitybooking_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='resident_group_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='resident_permission_set', to='auth.permission'),
        ),
    ]
